name: Publish to Modrinth

on:
  release:
    types: [published]
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3
        with:
          modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: ${{ github.ref_name }}
          version: ${{ github.ref_name }}
          version-type: release
          changelog: ${{ github.event.release.body || '' }}

          loaders: |
            fabric


          files: |
            build/libs/*.jar
          files-ignore: |
            *-sources.jar
            *-dev.jar
            *-unmapped.jar
